//Patterns foes from e to E string, steps from root.
//Zero means muted/unplayed string.

import { IChordShape } from '../types/Chord';

export const chordShapes: IChordShape[] = [
  {
    type: 'major',
    number: 1,
    tags: ['Movable', 'Bar'],
    inversion: 0,
    pattern: [1, 8, 5, 1, 8, 1],
  },
  {
    type: 'major',
    number: 2,
    tags: ['Movable', 'Bar'],
    inversion: 0,
    pattern: [8, 5, 1, 8, 1, 0],
  },
  {
    type: 'major',
    number: 3,
    tags: ['Movable', 'D-Shape'],
    inversion: 2,
    pattern: [5, 1, 8, 0, 0, 0],
  },
  {
    type: 'major',
    number: 4,
    tags: ['Movable'],
    inversion: 0,
    pattern: [0, 8, 5, 1, 0, 0],
  },
  {
    type: 'major',
    number: 5,
    tags: ['Movable', 'C-Shape'],
    inversion: 0,
    pattern: [0, 0, 8, 5, 1, 0],
  },
  {
    type: 'major',
    number: 6,
    tags: ['Movable'],
    inversion: 0,
    pattern: [8, 5, 1, 0, 0, 0],
  },
  {
    type: 'major',
    number: 7,
    tags: ['Movable'],
    inversion: 2,
    pattern: [0, 5, 1, 8, 0, 0],
  },
  {
    type: 'major',
    number: 8,
    tags: ['Movable'],
    inversion: 1,
    pattern: [1, 8, 5, 0, 0, 0],
  },
  {
    type: 'major6',
    number: 1,
    tags: ['Movable', 'Bar'],
    pattern: [10, 5, 1, 8, 1, 0],
  },
  {
    type: 'major6',
    number: 2,
    tags: ['Movable', 'Bar'],
    pattern: [0, 5, 10, 5, 1, 0],
  },
  {
    type: 'major6',
    number: 3,
    tags: ['Movable', 'Bar'],
    pattern: [0, 1, 10, 5, 1, 0],
  },
  {
    type: 'major6',
    number: 4,
    tags: ['Movable', 'Bar'],
    pattern: [10, 5, 1, 8, 0, 0],
  },
  {
    type: 'major6',
    number: 5,
    tags: ['Movable'],
    pattern: [0, 0, 10, 5, 1, 8],
  },
  {
    type: 'major6',
    number: 6,
    tags: ['Movable'],
    pattern: [1, 8, 5, 10, 0, 0],
  },
  {
    type: 'major6',
    number: 7,
    tags: ['Movable'],
    pattern: [0, 0, 8, 1, 10, 5],
  },
  {
    type: 'major6',
    number: 8,
    tags: ['Movable'],
    pattern: [0, 10, 5, 1, 8, 0],
  },
  {
    type: 'major6_9',
    number: 1,
    tags: ['Movable', 'Bar'],
    pattern: [1, 8, 15, 10, 5, 1],
  },
  {
    type: 'major6_9',
    number: 2,
    tags: ['Movable', 'Bar'],
    pattern: [8, 15, 10, 5, 1, 0],
  },
  {
    type: 'major7',
    number: 1,
    tags: ['Movable'],
    pattern: [12, 8, 5, 1, 0, 0],
  },
  {
    type: 'major7',
    number: 2,
    tags: ['Movable', 'Bar'],
    pattern: [1, 8, 5, 12, 8, 1],
  },
  {
    type: 'major7',
    number: 3,
    tags: ['Movable', 'Bar'],
    pattern: [5, 12, 8, 1, 0, 0],
  },
  {
    type: 'major7',
    number: 4,
    tags: ['Movable', 'Bar'],
    pattern: [8, 5, 12, 8, 1, 0],
  },
  {
    type: 'major7',
    number: 5,
    tags: ['Movable', 'Drop 2'],
    inversion: 2,
    pattern: [0, 12, 5, 1, 8, 0],
  },
  {
    type: 'major7',
    number: 6,
    inversion: 2,
    tags: ['Movable', 'Drop 2'],
    pattern: [0, 0, 12, 5, 1, 8],
  },
  {
    type: 'major7',
    number: 7,
    inversion: 2,
    tags: ['Movable', 'Drop 2'],
    pattern: [12, 5, 1, 8, 0, 0],
  },
  {
    type: 'major7',
    number: 8,
    tags: ['Movable', 'Drop 2'],
    pattern: [0, 0, 1, 8, 5, 12],
  },
  {
    type: 'major7',
    number: 9,
    inversion: 1,
    tags: ['Movable', 'Drop 2'],
    pattern: [0, 0, 8, 1, 12, 5],
  },
  {
    type: 'major7',
    number: 10,
    inversion: 1,
    tags: ['Movable', 'Drop 2'],
    pattern: [0, 8, 1, 12, 5, 0],
  },
  {
    type: 'major7',
    number: 11,
    tags: ['Movable', 'Drop 2'],
    pattern: [0, 1, 8, 5, 12, 0],
  },
  {
    type: 'major7',
    number: 12,
    inversion: 1,
    tags: ['Movable', 'Drop 2'],
    pattern: [8, 1, 12, 5, 0, 0],
  },
  {
    type: 'major7',
    number: 13,
    inversion: 2,
    tags: ['Movable', 'Drop 2'],
    pattern: [12, 5, 1, 8, 0, 0],
  },
  {
    type: 'major7',
    number: 14,
    tags: ['Movable', 'Drop 2'],
    pattern: [1, 8, 5, 12, 0, 0],
  },
  {
    type: 'major9',
    number: 1,
    tags: ['Movable'],
    pattern: [0, 15, 12, 5, 1, 0],
    extra: 'no 5th',
  },
  {
    type: 'major9',
    number: 2,
    tags: ['Movable', 'Bar'],
    pattern: [12, 8, 15, 1, 0, 0],
    extra: 'no 3rd',
  },
  {
    type: 'minor',
    number: 1,
    tags: ['Movable', 'Bar'],
    pattern: [1, 8, 4, 1, 8, 1],
  },
  {
    type: 'minor',
    number: 2,
    tags: ['Movable', 'Bar'],
    pattern: [8, 4, 1, 8, 1, 0],
  },
  {
    type: 'minor',
    number: 3,
    tags: ['Movable'],
    pattern: [0, 0, 8, 4, 1, 0],
  },
  {
    type: 'minor6',
    number: 1,
    tags: ['Movable', 'Bar'],
    pattern: [0, 1, 10, 4, 1, 0],
    extra: 'no 5th',
  },
  {
    type: 'minor6',
    number: 3,
    tags: ['Movable'],
    pattern: [0, 4, 10, 8, 1, 0],
    extra: 'no 5th',
  },
  {
    type: 'minor7',
    number: 1,
    tags: ['Movable'],
    pattern: [4, 11, 8, 1, 0, 0],
  },
  {
    type: 'minor7',
    number: 2,
    tags: ['Movable', 'Bar'],
    pattern: [8, 4, 11, 8, 1, 0],
  },
  {
    type: 'minor7',
    number: 3,
    tags: ['Movable', 'Bar'],
    pattern: [1, 8, 4, 11, 8, 1],
  },
  {
    type: 'minor7',
    number: 4,
    tags: ['Movable', 'Drop 2'],
    inversion: 2,
    pattern: [0, 0, 11, 4, 1, 8],
  },
  {
    type: 'minor7',
    number: 5,
    tags: ['Movable', 'Drop 2'],
    pattern: [0, 0, 1, 8, 4, 11],
  },
  {
    type: 'minor7',
    number: 6,
    tags: ['Movable', 'Drop 2'],
    inversion: 1,
    pattern: [0, 0, 8, 1, 11, 4],
  },
  {
    type: 'minor7',
    number: 7,
    tags: ['Movable', 'Drop 2'],
    inversion: 1,
    pattern: [0, 8, 1, 11, 4, 0],
  },
  {
    type: 'minor7',
    number: 8,
    tags: ['Movable', 'Drop 2'],
    inversion: 2,
    pattern: [0, 11, 4, 1, 8, 0],
  },
  {
    type: 'minor7',
    number: 9,
    tags: ['Movable', 'Drop 2'],
    pattern: [0, 1, 8, 4, 11, 0],
  },
  {
    type: 'minor7',
    number: 10,
    tags: ['Movable', 'Drop 2'],
    inversion: 1,
    pattern: [8, 1, 11, 4, 0, 0],
  },
  {
    type: 'minor7',
    number: 11,
    tags: ['Movable', 'Drop 2'],
    inversion: 2,
    pattern: [11, 4, 1, 8, 0, 0],
  },
  {
    type: 'minor7',
    number: 12,
    tags: ['Movable', 'Drop 2'],
    pattern: [1, 8, 4, 11, 0, 0],
  },
  {
    type: 'minor7♭5',
    number: 1,
    tags: ['Movable'],
    pattern: [0, 4, 11, 7, 1, 0],
  },
  {
    type: 'minor7♭5',
    number: 2,
    tags: ['Movable', 'Bar'],
    pattern: [4, 11, 7, 1, 0, 0],
  },
  {
    type: 'minor9',
    number: 1,
    tags: ['Movable', 'Bar'],
    pattern: [15, 8, 4, 11, 8, 1],
  },
  {
    type: 'minor9',
    number: 2,
    tags: ['Movable'],
    pattern: [0, 15, 11, 4, 1, 0],
    extra: 'no 5th',
  },
  {
    type: 'minor11',
    number: 1,
    tags: ['Movable', 'Bar'],
    pattern: [8, 4, 11, 6, 1, 0],
  },
  {
    type: 'dom7',
    number: 1,
    tags: ['Movable'],
    pattern: [5, 11, 8, 0, 0, 0],
    extra: 'no 1st',
  },
  {
    type: 'dom7',
    number: 2,
    tags: ['Movable'],
    pattern: [0, 0, 11, 5, 1, 0],
    extra: 'no 5th',
  },
  {
    type: 'dom7',
    number: 3,
    tags: ['Movable', 'Bar'],
    pattern: [1, 8, 5, 11, 8, 1],
  },
  {
    type: 'dom7',
    number: 4,
    tags: ['Movable', 'Bar'],
    pattern: [8, 5, 11, 8, 1, 0],
  },
  {
    type: 'dom7',
    number: 5,
    inversion: 2,
    tags: ['Movable', 'Drop 2'],
    pattern: [0, 0, 11, 5, 1, 8],
  },
  {
    type: 'dom7',
    number: 6,
    inversion: 2,
    tags: ['Movable', 'Drop 2'],
    pattern: [0, 11, 5, 1, 8, 0],
  },
  {
    type: 'dom7',
    number: 7,
    inversion: 2,
    tags: ['Movable', 'Drop 2'],
    pattern: [11, 5, 1, 8, 0, 0],
  },
  {
    type: 'dom7',
    number: 8,
    tags: ['Movable', 'Drop 2'],
    pattern: [0, 0, 1, 8, 5, 11],
  },
  {
    type: 'dom7',
    number: 9,
    inversion: 1,
    tags: ['Movable', 'Drop 2'],
    pattern: [0, 0, 8, 1, 11, 5],
  },
  {
    type: 'dom7',
    number: 10,
    inversion: 1,
    tags: ['Movable', 'Drop 2'],
    pattern: [0, 8, 1, 11, 5, 0],
  },
  {
    type: 'dom7',
    number: 11,
    tags: ['Movable', 'Drop 2'],
    pattern: [0, 1, 8, 5, 11, 0],
  },
  {
    type: 'dom7',
    number: 12,
    inversion: 1,
    tags: ['Movable', 'Drop 2'],
    pattern: [8, 1, 11, 5, 0, 0],
  },
  {
    type: 'dom7',
    number: 13,
    tags: ['Movable', 'Drop 2'],
    pattern: [1, 8, 5, 11, 0, 0],
  },
  {
    type: 'dom7♭5',
    number: 1,
    tags: ['Movable'],
    pattern: [0, 0, 5, 11, 7, 1],
  },
  {
    type: 'dom7♭5',
    number: 2,
    tags: ['Movable', 'Bar'],
    pattern: [0, 5, 11, 7, 1, 0],
  },
  {
    type: 'dom9',
    number: 1,
    pattern: [0, 8, 15, 11, 5, 0],
    extra: 'no 1st',
  },
  {
    type: 'dom9',
    number: 2,
    tags: ['Movable'],
    pattern: [8, 15, 11, 5, 1, 0],
  },
  {
    type: 'dom9',
    number: 3,
    tags: ['Movable', 'Bar'],
    pattern: [15, 8, 5, 11, 8, 1],
  },
  {
    type: 'dom11',
    number: 1,
    tags: ['Movable', 'Bar'],
    pattern: [8, 15, 11, 6, 1, 0],
    extra: 'no 3rd',
  },
  {
    type: 'aug',
    number: 1,
    tags: ['Movable'],
    pattern: [0, 0, 0, 9, 5, 1],
  },
  {
    type: 'aug',
    number: 2,
    tags: ['Movable'],
    inversion: 2,
    pattern: [0, 0, 5, 1, 9, 0],
  },
  {
    type: 'aug',
    number: 3,
    tags: ['Movable'],
    pattern: [0, 9, 5, 1, 9, 0],
  },
  {
    type: 'aug',
    number: 4,
    tags: ['Movable'],
    pattern: [1, 9, 5, 1, 0, 0],
  },
  {
    type: 'aug7',
    number: 1,
    pattern: [0, 1, 9, 5, 11, 0],
  },
  {
    type: 'dim',
    number: 1,
    tags: ['Movable'],
    pattern: [0, 7, 4, 1, 0, 0],
  },
  {
    type: 'dim',
    number: 2,
    tags: ['Movable', 'Bar'],
    pattern: [0, 0, 7, 4, 1, 0],
  },
  {
    type: 'dim',
    number: 3,
    tags: ['Movable', 'D-Shape'],
    inversion: 2,
    pattern: [0, 4, 1, 7, 0, 0],
  },
  {
    type: 'dim',
    number: 4,
    tags: ['Movable'],
    inversion: 1,
    pattern: [1, 7, 4, 0, 0, 0],
  },
  {
    type: 'dim',
    number: 5,
    tags: ['Movable'],
    pattern: [7, 4, 1, 0, 0, 0],
  },
  {
    type: 'dim7',
    number: 1,
    tags: ['Movable'],
    pattern: [0, 0, 4, 10, 7, 1],
  },
  {
    type: 'dim7',
    number: 2,
    tags: ['Movable'],
    pattern: [1, 7, 4, 10, 0, 0],
  },
  {
    type: 'dim7',
    number: 3,
    tags: ['Movable'],
    pattern: [7, 1, 10, 4, 0, 0],
  },
  {
    type: 'dim7',
    number: 4,
    tags: ['Movable'],
    pattern: [10, 4, 1, 7, 0, 0],
  },
  {
    type: 'dim7',
    number: 5,
    tags: ['Movable'],
    pattern: [4, 10, 7, 1, 0, 0],
  },
  {
    type: 'sus2',
    number: 1,
    tags: ['Movable'],
    pattern: [0, 0, 8, 3, 1, 0],
  },
  {
    type: 'sus2',
    number: 2,
    tags: ['Movable', 'Bar'],
    pattern: [8, 3, 1, 8, 1, 0],
  },
  {
    type: 'sus2',
    number: 3,
    tags: ['Movable'],
    pattern: [8, 3, 1, 0, 0, 0],
  },
  {
    type: 'sus2',
    number: 4,
    tags: ['Movable'],
    pattern: [1, 8, 3, 0, 0, 0],
  },
  {
    type: 'sus4',
    number: 1,
    tags: ['Movable', 'Bar'],
    pattern: [1, 8, 6, 1, 6, 1],
  },
  {
    type: 'sus4',
    number: 2,
    tags: ['Movable', 'Bar'],
    pattern: [8, 6, 1, 8, 1, 0],
  },
  {
    type: 'sus4',
    number: 3,
    tags: ['Movable'],
    pattern: [0, 8, 6, 1, 0, 0],
  },
  {
    type: '7sus4',
    number: 1,
    tags: ['Movable'],
    pattern: [0, 1, 11, 6, 1, 0],
    extra: 'no 5th',
  },
  {
    type: '7sus4',
    number: 2,
    tags: ['Movable', 'Bar'],
    pattern: [1, 8, 6, 11, 8, 1],
  },
  {
    type: 'add9',
    number: 1,
    pattern: [15, 8, 5, 1, 0, 0],
  },
  {
    type: 'add9',
    number: 2,
    tags: ['Movable'],
    pattern: [0, 15, 8, 5, 1, 0],
  },
];
